#!/usr/bin/env node
// count-lines.mjs — Release line-count report for Farm Tycoon.
//
// Every release of this project must state its line count, broken down by
// area, so CI can run it and anyone can reproduce it locally. This script is
// that source of truth: run `npm run count` (or `node tools/count-lines.mjs
// --json` for CI consumption).
//
// What it does:
//   - Counts total and non-blank lines per project area (src/, tools/,
//     styles+markup, docs, electron/).
//   - Names what is EXCLUDED and why: node_modules/, dist/, build/, fonts/
//     (vendored third-party binaries), design/ (a checked-in reference
//     produced by a design tool, not this project's code).
//   - Separates generated output (fonts/fonts.css, fonts/MANIFEST.json,
//     build/icon.*) from hand-written code — generated output is reported
//     but never counted as authored.
//   - Reports agent-vs-human authorship per SURVIVING line via `git blame`,
//     never by summing added lines from `git log` (churn is not authorship).
//   - Gives two totals: the project total (hand-written, non-excluded) and
//     a grand total of everything counted, with excluded rows visible.
//   - Self-checks that the authorship split sums to the line total, and
//     fails loudly if it does not.

import { execFileSync } from 'node:child_process';
import { readFileSync, statSync } from 'node:fs';
import { join, relative, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = fileURLToPath(new URL('..', import.meta.url));

// ---------------------------------------------------------------------------
// Area definitions: each area is a set of path globs (simple prefix/suffix
// matching, no dependency needed) resolved against `git ls-files`, so only
// tracked files are ever counted — nothing untracked, nothing ignored.
// ---------------------------------------------------------------------------

const AREAS = [
  {
    key: 'src',
    label: 'Project source (src/)',
    match: (p) => p.startsWith('src/'),
    authored: true,
  },
  {
    key: 'tools',
    label: 'Tests / tools (tools/)',
    match: (p) => p.startsWith('tools/'),
    authored: true,
  },
  {
    key: 'styles-markup',
    label: 'Styles & markup (styles.css, index.html)',
    match: (p) => p === 'styles.css' || p === 'index.html',
    authored: true,
  },
  {
    key: 'docs',
    label: 'Docs (*.md)',
    match: (p) => p.endsWith('.md'),
    authored: true,
  },
  {
    key: 'electron',
    label: 'Electron wrapper (electron/)',
    match: (p) => p.startsWith('electron/'),
    authored: true,
  },
  {
    key: 'root-config',
    label: 'Root config (package.json, package-lock.json, .gitignore, etc.)',
    match: (p) =>
      !p.includes('/') &&
      p !== 'styles.css' &&
      p !== 'index.html' &&
      !p.endsWith('.md'),
    authored: true,
  },
];

// Excluded areas: named and reported, never folded into the project total.
const EXCLUDED_AREAS = [
  {
    key: 'node_modules',
    label: 'node_modules/ (installed dependencies)',
    match: (p) => p.startsWith('node_modules/'),
    reason: 'installed third-party dependency tree, not this project\'s code',
  },
  {
    key: 'dist',
    label: 'dist/ (packaged installer output)',
    match: (p) => p.startsWith('dist/'),
    reason: 'build output, not source',
  },
  {
    key: 'build-generated',
    label: 'build/icon.* (generated icon)',
    match: (p) => p.startsWith('build/') && /^icon\./.test(p.slice('build/'.length)),
    reason: 'generated by tools/make-icon.mjs, not hand-written',
  },
  {
    key: 'build-other',
    label: 'build/ (other build output)',
    match: (p) => p.startsWith('build/'),
    reason: 'build output, not source',
  },
  {
    key: 'fonts-vendored',
    label: 'fonts/ (vendored third-party font binaries)',
    match: (p) => p.startsWith('fonts/') && !isGeneratedFontFile(p),
    reason: 'vendored third-party binaries, not this project\'s code',
  },
  {
    key: 'fonts-generated',
    label: 'fonts/fonts.css, fonts/MANIFEST.json (generated)',
    match: (p) => p.startsWith('fonts/') && isGeneratedFontFile(p),
    reason: 'generated by tools/vendor-fonts.mjs, not hand-written',
  },
  {
    key: 'design',
    label: 'design/ (checked-in design-tool reference)',
    match: (p) => p.startsWith('design/'),
    reason: "a checked-in reference produced by a design tool, not this project's code",
  },
];

function isGeneratedFontFile(p) {
  const rest = p.slice('fonts/'.length);
  return rest === 'fonts.css' || rest === 'MANIFEST.json';
}

// ---------------------------------------------------------------------------
// Git helpers
// ---------------------------------------------------------------------------

function git(args) {
  return execFileSync('git', args, {
    cwd: REPO_ROOT,
    encoding: 'utf8',
    maxBuffer: 1024 * 1024 * 64,
  });
}

function listTrackedFiles() {
  const out = git(['ls-files', '-z']);
  return out.split('\0').filter(Boolean);
}

// Binary/font extensions we never try to line-count even if a rule matches.
const BINARY_EXTS = new Set([
  '.woff', '.woff2', '.ttf', '.otf', '.eot',
  '.png', '.jpg', '.jpeg', '.gif', '.ico', '.icns', '.bmp', '.webp',
  '.zip', '.exe', '.dll', '.pdf',
]);

function isLikelyBinary(absPath) {
  const ext = extname(absPath).toLowerCase();
  if (BINARY_EXTS.has(ext)) return true;
  try {
    const buf = readFileSync(absPath);
    const sample = buf.subarray(0, Math.min(buf.length, 8000));
    // NUL byte in the sample is a strong binary signal.
    return sample.includes(0);
  } catch {
    return true; // unreadable => treat as binary/skip
  }
}

function countLines(absPath) {
  const raw = readFileSync(absPath, 'utf8');
  if (raw.length === 0) return { total: 0, nonBlank: 0 };
  // Split on line terminators without counting a trailing terminator as an
  // extra line — matches how `git blame` enumerates lines.
  const normalized = raw.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  const endsWithNewline = normalized.endsWith('\n');
  const body = endsWithNewline ? normalized.slice(0, -1) : normalized;
  if (body.length === 0) return { total: 0, nonBlank: 0 };
  const lines = body.split('\n');
  const nonBlank = lines.filter((l) => l.trim().length > 0).length;
  return { total: lines.length, nonBlank };
}

// ---------------------------------------------------------------------------
// git blame authorship per surviving line
// ---------------------------------------------------------------------------

// Cache of commit SHA -> { isAgent: bool }
const commitAgentCache = new Map();

function commitIsAgentAuthored(sha) {
  if (commitAgentCache.has(sha)) return commitAgentCache.get(sha);
  let isAgent = false;
  try {
    const raw = git(['show', '-s', '--format=%an%x00%B', sha]);
    const sep = raw.indexOf('\0');
    const authorName = raw.slice(0, sep);
    const body = raw.slice(sep + 1);
    if (authorName.trim() === 'Claude Fable 5') {
      isAgent = true;
    } else if (/Co-Authored-By:\s*Claude Fable 5\s*</i.test(body)) {
      isAgent = true;
    }
  } catch {
    isAgent = false;
  }
  commitAgentCache.set(sha, isAgent);
  return isAgent;
}

function blameAuthorship(relPath) {
  // Returns { human: n, agent: n, total: n } counted from git blame's
  // porcelain output, one row per surviving line in the current tree.
  let out;
  try {
    out = git(['blame', '--porcelain', '--', relPath]);
  } catch {
    // File has no blame history (e.g. untracked) — treat all lines as
    // unattributed/human by default; but since we only iterate tracked
    // files this should not normally happen.
    return { human: 0, agent: 0, total: 0, blamed: false };
  }
  let human = 0;
  let agent = 0;
  let total = 0;
  const lines = out.split('\n');
  for (const line of lines) {
    // Every physical line of the blamed file gets exactly one commit-header
    // line: "<sha> <orig-line> <final-line> [<lines-in-group>]". The
    // trailing group-size number, when present, is metadata about how many
    // header lines follow for this commit's contiguous run — it is NOT a
    // multiplier on this header line. Each header line == exactly 1 line.
    const m = /^([0-9a-f]{40}) \d+ \d+(?: \d+)?$/.exec(line);
    if (!m) continue;
    const sha = m[1];
    const isAgent = commitIsAgentAuthored(sha);
    total += 1;
    if (isAgent) agent += 1;
    else human += 1;
  }
  return { human, agent, total, blamed: true };
}

// ---------------------------------------------------------------------------
// Build the report
// ---------------------------------------------------------------------------

function classify(relPath) {
  for (const area of EXCLUDED_AREAS) {
    if (area.match(relPath)) return { kind: 'excluded', area };
  }
  for (const area of AREAS) {
    if (area.match(relPath)) return { kind: 'authored', area };
  }
  return { kind: 'other', area: null };
}

function buildReport() {
  const files = listTrackedFiles();

  const areaRows = new Map(); // key -> { label, total, nonBlank, files, human, agent, unattributed }
  const excludedRows = new Map(); // key -> { label, reason, total, nonBlank, files }
  const otherFiles = [];

  const initAuthored = (a) => ({
    label: a.label,
    total: 0,
    nonBlank: 0,
    files: 0,
    human: 0,
    agent: 0,
    blameTotal: 0,
  });
  for (const a of AREAS) areaRows.set(a.key, initAuthored(a));

  const initExcluded = (a) => ({
    label: a.label,
    reason: a.reason,
    total: 0,
    nonBlank: 0,
    files: 0,
  });
  for (const a of EXCLUDED_AREAS) excludedRows.set(a.key, initExcluded(a));

  for (const relPath of files) {
    const absPath = join(REPO_ROOT, relPath);
    let stat;
    try {
      stat = statSync(absPath);
    } catch {
      continue; // deleted-but-tracked edge case; skip
    }
    if (!stat.isFile()) continue;

    const { kind, area } = classify(relPath);

    if (kind === 'excluded') {
      if (isLikelyBinary(absPath)) {
        // Binary vendored assets (e.g. .woff2 fonts) contribute a file
        // count but no meaningful line count.
        const row = excludedRows.get(area.key);
        row.files += 1;
        continue;
      }
      const { total, nonBlank } = countLines(absPath);
      const row = excludedRows.get(area.key);
      row.total += total;
      row.nonBlank += nonBlank;
      row.files += 1;
      continue;
    }

    if (kind === 'other') {
      otherFiles.push(relPath);
      continue;
    }

    // authored
    if (isLikelyBinary(absPath)) continue; // shouldn't happen for these areas
    const { total, nonBlank } = countLines(absPath);
    const row = areaRows.get(area.key);
    row.total += total;
    row.nonBlank += nonBlank;
    row.files += 1;

    const blame = blameAuthorship(relPath);
    row.human += blame.human;
    row.agent += blame.agent;
    row.blameTotal += blame.total;
  }

  return { areaRows, excludedRows, otherFiles };
}

// ---------------------------------------------------------------------------
// Self-consistency check
// ---------------------------------------------------------------------------

function verifyConsistency(areaRows) {
  let lineTotal = 0;
  let blameTotal = 0;
  let humanTotal = 0;
  let agentTotal = 0;
  for (const row of areaRows.values()) {
    lineTotal += row.total;
    blameTotal += row.blameTotal;
    humanTotal += row.human;
    agentTotal += row.agent;
  }
  const problems = [];
  if (humanTotal + agentTotal !== blameTotal) {
    problems.push(
      `authorship split (human ${humanTotal} + agent ${agentTotal} = ${humanTotal + agentTotal}) ` +
      `does not equal the blamed total (${blameTotal})`
    );
  }
  if (blameTotal !== lineTotal) {
    problems.push(
      `git blame total (${blameTotal}) does not equal the counted line total (${lineTotal}). ` +
      `A common cause: counting a file's trailing newline as an extra line, which git blame does not.`
    );
  }
  return { ok: problems.length === 0, problems, lineTotal, blameTotal, humanTotal, agentTotal };
}

// ---------------------------------------------------------------------------
// Output
// ---------------------------------------------------------------------------

function main() {
  const args = process.argv.slice(2);
  const asJson = args.includes('--json');

  const { areaRows, excludedRows, otherFiles } = buildReport();
  const check = verifyConsistency(areaRows);

  let projectTotal = 0;
  let projectNonBlank = 0;
  for (const row of areaRows.values()) {
    projectTotal += row.total;
    projectNonBlank += row.nonBlank;
  }

  let excludedTotal = 0;
  let excludedNonBlank = 0;
  for (const row of excludedRows.values()) {
    excludedTotal += row.total;
    excludedNonBlank += row.nonBlank;
  }

  const grandTotal = projectTotal + excludedTotal;
  const grandNonBlank = projectNonBlank + excludedNonBlank;

  const authorshipMethod =
    'Per-surviving-line git blame. A commit is agent-authored when its author ' +
    'is "Claude Fable 5" or its message carries a "Co-Authored-By: Claude Fable 5" trailer. ' +
    'Lines added and later deleted are not counted (churn is not authorship).';

  if (asJson) {
    const payload = {
      generatedAt: new Date().toISOString(),
      excludedNote:
        'node_modules/, dist/, build/ (except icon.* which is separately flagged generated), ' +
        'fonts/ (vendored binaries; fonts.css and MANIFEST.json are separately flagged generated), ' +
        "and design/ (checked-in design-tool reference) are excluded from the project total.",
      areas: Object.fromEntries(
        [...areaRows.entries()].map(([key, row]) => [key, row])
      ),
      excluded: Object.fromEntries(
        [...excludedRows.entries()].map(([key, row]) => [key, row])
      ),
      otherUncategorizedFiles: otherFiles,
      totals: {
        project: { total: projectTotal, nonBlank: projectNonBlank },
        excluded: { total: excludedTotal, nonBlank: excludedNonBlank },
        grand: { total: grandTotal, nonBlank: grandNonBlank },
      },
      authorship: {
        method: authorshipMethod,
        human: check.humanTotal,
        agent: check.agentTotal,
      },
      consistencyCheck: {
        ok: check.ok,
        problems: check.problems,
      },
    };
    if (!check.ok) {
      process.stderr.write(JSON.stringify(payload, null, 2) + '\n');
      process.stderr.write('\ncount-lines: consistency check FAILED, see problems[] above.\n');
      process.exit(1);
    }
    process.stdout.write(JSON.stringify(payload, null, 2) + '\n');
    return;
  }

  // Human-readable table
  const lines = [];
  lines.push('Farm Tycoon — line count report');
  lines.push('='.repeat(60));
  lines.push('');
  lines.push('Project areas (hand-written, counted toward project total):');
  lines.push('');
  const header = pad('Area', 42) + pad('Files', 7) + pad('Total', 8) + pad('NonBlank', 9);
  lines.push(header);
  lines.push('-'.repeat(header.length));
  for (const row of areaRows.values()) {
    lines.push(
      pad(row.label, 42) + pad(String(row.files), 7) + pad(String(row.total), 8) + pad(String(row.nonBlank), 9)
    );
  }
  lines.push('-'.repeat(header.length));
  lines.push(
    pad('PROJECT TOTAL', 42) + pad('', 7) + pad(String(projectTotal), 8) + pad(String(projectNonBlank), 9)
  );
  lines.push('');
  lines.push('Excluded (named, not counted in project total):');
  lines.push('');
  for (const row of excludedRows.values()) {
    lines.push(`  - ${row.label}: ${row.total} lines / ${row.files} files — ${row.reason}`);
  }
  lines.push('');
  lines.push(
    `GRAND TOTAL (project + excluded, everything counted): ${grandTotal} lines (${grandNonBlank} non-blank)`
  );
  if (otherFiles.length > 0) {
    lines.push('');
    lines.push(`Note: ${otherFiles.length} tracked file(s) matched no area rule and were not counted:`);
    for (const f of otherFiles.slice(0, 20)) lines.push(`  - ${f}`);
    if (otherFiles.length > 20) lines.push(`  ... and ${otherFiles.length - 20} more`);
  }
  lines.push('');
  lines.push('Authorship (per surviving line, via git blame):');
  lines.push(`  Method: ${authorshipMethod}`);
  lines.push(`  Human-authored:  ${check.humanTotal} lines`);
  lines.push(`  Agent-authored:  ${check.agentTotal} lines`);
  lines.push('');
  lines.push('Self-consistency check:');
  if (check.ok) {
    lines.push(
      `  OK — authorship split (${check.humanTotal} + ${check.agentTotal} = ${check.humanTotal + check.agentTotal}) ` +
      `equals git blame total (${check.blameTotal}) equals counted line total (${check.lineTotal}).`
    );
  } else {
    lines.push('  FAILED:');
    for (const p of check.problems) lines.push(`    - ${p}`);
  }

  const text = lines.join('\n') + '\n';
  if (!check.ok) {
    process.stderr.write(text);
    process.exit(1);
  }
  process.stdout.write(text);
}

function pad(s, width) {
  s = String(s);
  return s.length >= width ? s + ' ' : s + ' '.repeat(width - s.length);
}

main();
