// vendor-fonts.mjs — download every font file the design's Google Fonts query returns and
// emit a local @font-face stylesheet plus a SHA-256 manifest. Run: node tools/vendor-fonts.mjs
//
// The project forbids CDN assets, so the fonts must be local. The reason this is a script and
// not a one-off manual download: ONE family query answers with dozens of @font-face blocks —
// one per weight, per style, and per unicode-range subset. This query returns 27. Vendoring
// "the two fonts" by hand would ship 2 files, collapse three weights into one, and silently
// drop every non-latin subset, with no error anywhere.
//
// Rules this encodes, each of which is a way to get it subtly wrong:
//   - Send a modern browser User-Agent, or Google serves an older format than woff2.
//   - Preserve font-weight and unicode-range EXACTLY; rewrite only src. Drop the ranges and the
//     browser downloads everything for one accented character; collapse the weights and the
//     design's typographic hierarchy quietly flattens.
//   - Never declare an axis the file does not have. These are static faces, so no variable
//     font-weight range and no font-variation-settings.
//   - Record a SHA-256 per file and fail loudly rather than shipping a partial set: a font that
//     half-downloaded looks exactly like a font that is fine.

import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';
const QUERY = 'https://fonts.googleapis.com/css2?family=Baloo+2:wght@600;700;800&family=Nunito:wght@700;800;900&display=swap';
const OUT_DIR = 'fonts';

const slug = (family, weight, style, idx) =>
  `${family.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${weight}${style === 'italic' ? 'i' : ''}-${idx}.woff2`;

const css = await fetch(QUERY, { headers: { 'User-Agent': UA } }).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts CSS failed: HTTP ${r.status}`);
  return r.text();
});

// Parse each @font-face block, keeping every declaration we must preserve verbatim.
const blocks = [...css.matchAll(/@font-face\s*\{([^}]+)\}/g)].map((m) => m[1]);
if (blocks.length === 0) throw new Error('no @font-face blocks parsed — the CSS shape changed');

const field = (b, name) => (b.match(new RegExp(`${name}:\\s*([^;]+);`)) || [])[1]?.trim();
const faces = blocks.map((b, i) => {
  const family = (field(b, 'font-family') || '').replace(/['"]/g, '');
  const weight = field(b, 'font-weight');
  const style = field(b, 'font-style') || 'normal';
  const range = field(b, 'unicode-range');
  const url = (b.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
  if (!family || !weight || !url) throw new Error(`@font-face block ${i} is missing family, weight or url`);
  return { family, weight, style, range, url, file: slug(family, weight, style, i) };
});

await mkdir(OUT_DIR, { recursive: true });
const manifest = [];
for (const f of faces) {
  const res = await fetch(f.url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${f.file}: HTTP ${res.status} — refusing to ship a partial set`);
  const buf = Buffer.from(await res.arrayBuffer());
  // woff2 files begin with the signature 'wOF2'. A truncated or error-page download would not.
  if (buf.subarray(0, 4).toString('latin1') !== 'wOF2')
    throw new Error(`${f.file}: not a woff2 file (bad signature) — refusing to ship it`);
  await writeFile(path.join(OUT_DIR, f.file), buf);
  manifest.push({ file: f.file, family: f.family, weight: f.weight, style: f.style,
                  bytes: buf.length, sha256: createHash('sha256').update(buf).digest('hex'), source: f.url });
}

const rules = faces.map((f) => [
  '@font-face {',
  `  font-family: '${f.family}';`,
  `  font-style: ${f.style};`,
  `  font-weight: ${f.weight};`,
  '  font-display: swap;',
  `  src: url('./${f.file}') format('woff2');`,
  ...(f.range ? [`  unicode-range: ${f.range};`] : []),
  '}',
].join('\n')).join('\n\n');

await writeFile(path.join(OUT_DIR, 'fonts.css'),
  `/* Generated by tools/vendor-fonts.mjs — do not edit by hand.\n` +
  `   ${faces.length} faces vendored locally. font-weight and unicode-range are preserved\n` +
  `   exactly as Google served them; only src is rewritten. No CDN at runtime. */\n\n${rules}\n`);

await writeFile(path.join(OUT_DIR, 'MANIFEST.json'), JSON.stringify({ query: QUERY, faces: manifest }, null, 2) + '\n');

const byFamily = manifest.reduce((a, m) => ((a[m.family] = (a[m.family] || 0) + 1), a), {});
console.log(`vendored ${manifest.length} faces:`, byFamily);
console.log(`total ${(manifest.reduce((s, m) => s + m.bytes, 0) / 1024).toFixed(0)} KiB into ${OUT_DIR}/`);
